language: go
go: 
  - 1.5.2
  - release
  - tip

before_install:
  - go get github.com/amahi/spdy
  - go get golang.org/x/net/context
  - go get github.com/amahi/spdy
  - go get github.com/stretchr/testify
  - go get github.com/SlyMarbo/spdy
  - go get github.com/davecgh/go-spew/spew

install: make tools

script: make travis
